Fix link errors in liblogic.a: "undefined referecne to IdleWorkerSupply::IdleWorkerSupply(Worker &)" and "undefined reference to "IdleWorkerSupply::set_economy(Economy *)". (liblogic.o contains worker.o, which depends on these functions from idleworkersupply.o, which go into libeconomy.o. Therefore libeconomy.a must be created before liblogic.a. It is really strange to have the economy code outside the logic directory because the economy code is certainly a part of the logic code (like everything in namespace Widelands).
git-svn-id: https://widelands.svn.sourceforge.net/svnroot/widelands/trunk@4077 37b2a8de-5219-0410-9f54-a31bc463ab9c