abstract_node.h: include missing <cstdint>
Without the change build fails on upcoming gcc-15 as:

    src/base/format/abstract_node.h:24:12: error: found ':' in nested-name-specifier, expected '::'
       24 | enum Flags : uint8_t {
          |            ^