training_attribute.h: include missing <cstdint>
Without the change build fails on upcoming gcc-15 as:

    In file included from src/logic/map_objects/tribes/requirements.h:27:
    src/logic/map_objects/tribes/training_attribute.h:28:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
       28 | enum class TrainingAttribute : uint8_t { kHealth = 0, kAttack, kDefense, kEvade, kTotal = 100 };
          | ~~~~ ^~~~~
          |      -----
    src/logic/map_objects/tribes/training_attribute.h:28:30: error: found ':' in nested-name-specifier, expected '::'
       28 | enum class TrainingAttribute : uint8_t { kHealth = 0, kAttack, kDefense, kEvade, kTotal = 100 };
          |                              ^
          |                              ::